#!/usr/bin/env python
"""Apply recurrent tempered history to a uniformly sampled Chua trajectory.

The trajectory is generated by the integer-order Chua ODE and is used only as
a realistic three-channel sampled history.  Applying a fractional operator to
those samples does **not** turn it into a fractional Chua solution and does not
establish chaos, attraction, or hiddenness.  The example compares the GNGF2
Fast Method II result with an independent direct ``O(d*N^2)`` convolution.
"""

from __future__ import annotations

import json
from typing import Any

import numpy as np

from hidden_attractors.fractional import (
    TEMPERED_CAPUTO_INITIAL_CONDITION,
    tempered_fast_multistep_history,
)
from hidden_attractors.solvers.integer import dop853_q1_integrate
from hidden_attractors.systems.builtins import chua_system


def _gngf2_weights(order: float, count: int) -> np.ndarray:
    gl = np.empty(count, dtype=np.float64)
    gl[0] = 1.0
    for lag in range(1, count):
        gl[lag] = ((lag - 1.0 - order) / lag) * gl[lag - 1]
    weights = (1.0 + 0.5 * order) * gl
    if count > 1:
        weights[1:] -= 0.5 * order * gl[:-1]
    return weights


def _direct_componentwise_caputo(
    samples: np.ndarray,
    orders: np.ndarray,
    tempering: np.ndarray,
    step: float,
) -> np.ndarray:
    count, dimension = samples.shape
    output = np.empty_like(samples)
    lags = np.arange(count, dtype=np.float64)
    for component in range(dimension):
        weights = _gngf2_weights(float(orders[component]), count)
        damped = weights * np.exp(
            -float(tempering[component]) * step * lags
        )
        raw = np.convolve(samples[:, component], damped)[:count]
        raw -= (
            samples[0, component]
            * np.exp(-float(tempering[component]) * step * lags)
            * np.cumsum(weights)
        )
        raw[0] = 0.0
        output[:, component] = raw / step ** float(orders[component])
    return output


def run_example() -> dict[str, Any]:
    """Return a compact, JSON-serializable parity and scope record."""

    step = 0.005
    system = chua_system("nonsmooth")
    trajectory, status = dop853_q1_integrate(
        lambda state: system.evaluate(state),
        np.array([0.1, 0.0, 0.0]),
        t_final=4.0,
        h=step,
        max_step=step,
        div_threshold=120.0,
    )
    if status != "ok":
        raise RuntimeError(f"integer Chua source trajectory failed: {status}")
    times = trajectory[:, 0]
    states = np.ascontiguousarray(trajectory[:, 1:])
    orders = np.array([0.48, 0.67, 0.83])
    tempering = np.array([0.10, 0.35, 0.70])

    fast = tempered_fast_multistep_history(
        states,
        orders,
        tempering=tempering,
        multistep_method="gngf2",
        definition="tempered_caputo",
        times=times,
        lower_terminal=0.0,
        initial_condition_semantics=TEMPERED_CAPUTO_INITIAL_CONDITION,
        local_history_steps=50,
        relative_tolerance=1.0e-9,
        backend="numba",
    )
    direct = _direct_componentwise_caputo(states, orders, tempering, step)
    maximum_difference = float(np.max(np.abs(fast.values - direct)))

    return {
        "source_system": system.name,
        "source_solver": "integer_q1_dop853_uniform_output",
        "source_status": status,
        "sample_count": int(states.shape[0]),
        "dimension": int(states.shape[1]),
        "step": step,
        "orders": orders.tolist(),
        "tempering": tempering.tolist(),
        "operator_definition": fast.definition,
        "multistep_method": fast.multistep_method,
        "backend": fast.backend,
        "local_history_steps": fast.local_history_steps,
        "quadrature_points": fast.quadrature_points,
        "compression_tolerance_satisfied": (
            fast.compression_tolerance_satisfied
        ),
        "l1_relative_weight_error": fast.l1_relative_weight_error.tolist(),
        "maximum_fast_direct_difference": maximum_difference,
        "maximum_reported_operator_error_bound": float(
            np.max(fast.operator_absolute_error_bound)
        ),
        "finite_values": bool(np.all(np.isfinite(fast.values))),
        "evidence_scope": (
            "operator parity on an integer Chua sampled history; not a "
            "fractional Chua solve and not evidence of chaos, attraction, "
            "or hiddenness"
        ),
    }


if __name__ == "__main__":
    print(json.dumps(run_example(), indent=2, sort_keys=True))
