"""Post-processing helpers for parameter scans and bifurcation diagrams.

These helpers do not replace continuation packages such as PyDSTool. They take
trajectories produced by this project and extract observable values that can be
plotted as a bifurcation diagram for the current study systems.

Reference notes:
    This module implements trajectory post-processing only. Numerical
    continuation, branch tracking, and full bifurcation analysis should cite and
    delegate to a dedicated continuation package when used. See
    ``docs/code_reference_map.md`` and ``docs/external_tools.md``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable, Mapping, Sequence

import numpy as np


OBSERVABLE_COLUMNS = {"t": 0, "x": 1, "y": 2, "z": 3}


@dataclass(frozen=True)
class BifurcationPoint:
    """One observable value associated with one parameter value."""

    parameter: float
    observable: float
    time: float
    index: int
    kind: str

    def as_dict(self) -> dict[str, float | int | str]:
        return {
            "parameter": self.parameter,
            "observable": self.observable,
            "time": self.time,
            "index": self.index,
            "kind": self.kind,
        }


def observable_column(observable: str | int) -> int:
    """Return the trajectory column index for an observable."""

    if isinstance(observable, str):
        key = observable.strip().lower()
        if key not in OBSERVABLE_COLUMNS:
            raise ValueError(f"Unknown observable {observable!r}; use one of {sorted(OBSERVABLE_COLUMNS)} or an integer column.")
        return OBSERVABLE_COLUMNS[key]
    col = int(observable)
    if col < 0:
        raise ValueError("observable column must be non-negative")
    return col


def trajectory_tail(traj: np.ndarray, *, t_start: float | None = None) -> np.ndarray:
    """Return the post-transient part of a trajectory with columns ``t,x,y,z``."""

    X = np.asarray(traj, dtype=float)
    if X.ndim != 2 or X.shape[1] < 2:
        raise ValueError("trajectory must be a 2D array with at least columns t and one observable")
    if t_start is None:
        return X
    return X[X[:, 0] >= float(t_start)]


def local_extrema(values: Sequence[float], *, mode: str = "maxima") -> np.ndarray:
    """Return indices of local extrema in a one-dimensional series."""

    y = np.asarray(values, dtype=float)
    if y.size < 3:
        return np.arange(y.size, dtype=int)
    left = y[1:-1] - y[:-2]
    right = y[1:-1] - y[2:]
    if mode == "maxima":
        mask = (left >= 0.0) & (right >= 0.0)
    elif mode == "minima":
        mask = (left <= 0.0) & (right <= 0.0)
    elif mode == "both":
        mask = ((left >= 0.0) & (right >= 0.0)) | ((left <= 0.0) & (right <= 0.0))
    elif mode == "sample":
        return np.arange(y.size, dtype=int)
    else:
        raise ValueError("mode must be 'maxima', 'minima', 'both', or 'sample'")
    return np.where(mask)[0] + 1


def _scan_item(item: Mapping[str, Any] | tuple[float, np.ndarray], parameter_key: str) -> tuple[float, np.ndarray]:
    if isinstance(item, Mapping):
        if "trajectory" not in item:
            raise KeyError("scan mapping must contain a 'trajectory' entry")
        if parameter_key not in item:
            raise KeyError(f"scan mapping must contain parameter key {parameter_key!r}")
        return float(item[parameter_key]), np.asarray(item["trajectory"], dtype=float)
    parameter, trajectory = item
    return float(parameter), np.asarray(trajectory, dtype=float)


def bifurcation_points_from_trajectories(
    scans: Iterable[Mapping[str, Any] | tuple[float, np.ndarray]],
    *,
    parameter_key: str = "parameter",
    observable: str | int = "x",
    t_start: float | None = None,
    mode: str = "maxima",
    max_points_per_parameter: int = 250,
) -> list[BifurcationPoint]:
    """Extract bifurcation-diagram points from a parameter scan.

    Parameters
    ----------
    scans:
        Iterable of ``(parameter, trajectory)`` tuples or dictionaries with
        ``parameter_key`` and ``trajectory``.
    observable:
        Column to analyze. Use ``"x"``, ``"y"``, ``"z"``, ``"t"`` or an integer
        trajectory column.
    t_start:
        Transient cutoff. Use this to remove early-time dynamics.
    mode:
        ``"maxima"``, ``"minima"``, ``"both"``, or ``"sample"``.

    Notes
    -----
    This is post-processing for trajectories already generated by this
    repository. For numerical continuation and branch tracking, use a dedicated
    continuation package such as PyDSTool when compatible with the environment.
    """

    col = observable_column(observable)
    points: list[BifurcationPoint] = []
    for item in scans:
        parameter, trajectory = _scan_item(item, parameter_key)
        tail = trajectory_tail(trajectory, t_start=t_start)
        if tail.size == 0:
            continue
        if col >= tail.shape[1]:
            raise ValueError(f"observable column {col} exceeds trajectory width {tail.shape[1]}")
        idx = local_extrema(tail[:, col], mode=mode)
        if max_points_per_parameter > 0 and idx.size > max_points_per_parameter:
            select = np.linspace(0, idx.size - 1, int(max_points_per_parameter), dtype=int)
            idx = idx[select]
        for i in idx:
            points.append(
                BifurcationPoint(
                    parameter=parameter,
                    observable=float(tail[i, col]),
                    time=float(tail[i, 0]),
                    index=int(i),
                    kind=mode,
                )
            )
    return points


def bifurcation_summary(points: Sequence[BifurcationPoint]) -> dict[str, float | int]:
    """Return simple summary statistics for extracted bifurcation points."""

    if not points:
        return {"n_points": 0}
    params = np.array([p.parameter for p in points], dtype=float)
    values = np.array([p.observable for p in points], dtype=float)
    return {
        "n_points": int(values.size),
        "parameter_min": float(np.min(params)),
        "parameter_max": float(np.max(params)),
        "observable_min": float(np.min(values)),
        "observable_max": float(np.max(values)),
    }
