"""Bandt--Pompe ordinal-pattern distributions and permutation entropy.

Stability: experimental

This module implements a deterministic local estimator for scalar sampled
signals.  It supports trajectories generated by integer or fractional solvers
through :class:`~hidden_attractors.analysis.contracts.TrajectoryInput`, while
retaining sampling, projection, derivative, order, prehistory, and memory
provenance.  A finite plug-in entropy is a data diagnostic; it is not proof of
Kolmogorov--Sinai entropy, chaos, attraction, or hiddenness.

References
----------
C. Bandt and B. Pompe, "Permutation Entropy: A Natural Complexity Measure for
Time Series," Physical Review Letters 88 (2002), 174102.
https://doi.org/10.1103/PhysRevLett.88.174102

V. A. Unakafova and K. Keller, "Efficiently Measuring Complexity on the Basis
of Real-World Data," Entropy 15 (2013), 4392--4415.
https://doi.org/10.3390/e15104392

F. Traversaro et al., "Bandt--Pompe Symbolization Dynamics for Time Series
with Tied Values: A Data-Driven Approach," Chaos 28 (2018), 075502.
https://doi.org/10.1063/1.5022021

A. A. Rey et al., "The Asymptotic Distribution of the Permutation Entropy,"
Chaos 33 (2023), 113108. https://doi.org/10.1063/5.0171508
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field, is_dataclass
import math
from operator import index as operator_index
from types import MappingProxyType
from typing import Any, Literal, Mapping, Sequence

import numba
import numpy as np
from numba import njit

from .contracts import AnalysisResult, TrajectoryInput


TiePolicy = Literal["stable_index", "omit", "raise"]
Backend = Literal["auto", "native_c", "numba", "python"]

PERMUTATION_ENTROPY_REFERENCE_DOIS = (
    "10.1103/PhysRevLett.88.174102",
    "10.3390/e15104392",
    "10.1063/1.5022021",
    "10.1063/5.0171508",
)
PERMUTATION_ENTROPY_EVIDENCE_SCOPE = (
    "finite_sample_empirical_ordinal_pattern_diagnostic"
)
PERMUTATION_ENTROPY_MAX_EMBEDDING_DIMENSION = 10
PERMUTATION_ENTROPY_MAX_PATTERN_STATES = math.factorial(
    PERMUTATION_ENTROPY_MAX_EMBEDDING_DIMENSION
)
# Host measurements are retained by the benchmark, while this conservative
# dimension-aware policy avoids the large-histogram OpenMP/atomic penalty at
# m=9 and m=10. ``None`` means that automatic dispatch remains on Numba; users
# can still request ``backend="native_c"`` explicitly for their own workload.
PERMUTATION_ENTROPY_NATIVE_AUTO_WINDOW_THRESHOLDS: Mapping[int, int | None] = (
    MappingProxyType(
        {
            2: 131_072,
            3: 32_768,
            4: 32_768,
            5: 32_768,
            6: 32_768,
            7: 32_768,
            8: 131_072,
            9: None,
            10: None,
        }
    )
)
PERMUTATION_ENTROPY_NATIVE_AUTO_MIN_WINDOWS = min(
    threshold
    for threshold in PERMUTATION_ENTROPY_NATIVE_AUTO_WINDOW_THRESHOLDS.values()
    if threshold is not None
)

_TIE_POLICY_CODES = {"stable_index": 0, "omit": 1, "raise": 2}
_BACKENDS = frozenset({"auto", "native_c", "numba", "python"})


def _readonly_array(values: Any, dtype: np.dtype | type) -> np.ndarray:
    result = np.array(values, dtype=dtype, copy=True, order="C")
    result.setflags(write=False)
    return result


def _freeze_metadata(value: Any, *, path: str) -> Any:
    if isinstance(value, np.generic):
        return _freeze_metadata(value.item(), path=path)
    if isinstance(value, np.ndarray):
        return tuple(
            _freeze_metadata(item, path=f"{path}[{index}]")
            for index, item in enumerate(value.tolist())
        )
    if isinstance(value, Mapping):
        copied: dict[str, Any] = {}
        for key, item in value.items():
            if not isinstance(key, str):
                raise TypeError(f"{path} contains a non-string mapping key.")
            copied[key] = _freeze_metadata(item, path=f"{path}.{key}")
        return MappingProxyType(copied)
    if isinstance(value, (list, tuple)):
        return tuple(
            _freeze_metadata(item, path=f"{path}[{index}]")
            for index, item in enumerate(value)
        )
    if value is None or isinstance(value, (str, bool, int)):
        return value
    if isinstance(value, float):
        if not np.isfinite(value):
            raise TypeError(f"{path} contains a non-finite float.")
        return value
    raise TypeError(f"{path} contains unsupported value {type(value).__name__}.")


def _readonly_mapping(values: Mapping[str, Any]) -> Mapping[str, Any]:
    frozen = _freeze_metadata(values, path="metadata")
    if not isinstance(frozen, Mapping):
        raise TypeError("metadata must be a mapping.")
    return frozen


def _nonempty_text(value: Any, *, name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{name} must be a non-empty string.")
    return value.strip()


def _strict_integer(
    value: Any,
    *,
    name: str,
    minimum: int,
    maximum: int | None = None,
) -> int:
    if isinstance(value, (bool, np.bool_)):
        raise TypeError(f"{name} must be an integer, not Boolean.")
    try:
        result = int(operator_index(value))
    except TypeError as exc:
        raise TypeError(f"{name} must be an integer.") from exc
    if result < minimum:
        raise ValueError(f"{name} must be at least {minimum}.")
    if maximum is not None and result > maximum:
        raise ValueError(f"{name} must be at most {maximum}.")
    return result


def _normalize_tie_policy(value: Any) -> tuple[str, int]:
    if not isinstance(value, str):
        raise TypeError("tie_policy must be a string.")
    normalized = value.strip()
    if normalized not in _TIE_POLICY_CODES:
        raise ValueError("tie_policy must be 'stable_index', 'omit', or 'raise'.")
    return normalized, _TIE_POLICY_CODES[normalized]


def _normalize_backend(value: Any) -> str:
    if not isinstance(value, str):
        raise TypeError("backend must be a string.")
    normalized = value.strip()
    if normalized not in _BACKENDS:
        raise ValueError("backend must be 'auto', 'native_c', 'numba', or 'python'.")
    return normalized


def _factorial(value: int) -> int:
    result = 1
    for factor in range(2, value + 1):
        result *= factor
    return result


def _automatic_backend(total_windows: int, embedding_dimension: int) -> str:
    threshold = PERMUTATION_ENTROPY_NATIVE_AUTO_WINDOW_THRESHOLDS[
        embedding_dimension
    ]
    if threshold is not None and total_windows >= threshold:
        return "native_c"
    return "numba"


@njit(cache=True, nogil=True)
def _ordinal_pattern_counts_numba(
    signal: np.ndarray,
    embedding_dimension: int,
    delay: int,
    tie_policy_code: int,
) -> tuple[np.ndarray, int, int]:
    """Count lexicographic Lehmer ranks for forward ordinal windows."""

    state_count = 1
    for factor in range(2, embedding_dimension + 1):
        state_count *= factor
    counts = np.zeros(state_count, dtype=np.uint64)
    total_windows = signal.size - (embedding_dimension - 1) * delay
    tied_windows = 0
    first_tied_window = -1
    order = np.empty(embedding_dimension, dtype=np.int64)

    for start in range(total_windows):
        tied = False
        for left in range(embedding_dimension):
            left_value = signal[start + left * delay]
            for right in range(left + 1, embedding_dimension):
                if left_value == signal[start + right * delay]:
                    tied = True
        if tied:
            tied_windows += 1
            if first_tied_window < 0:
                first_tied_window = start
            if tie_policy_code == 1 or tie_policy_code == 2:
                continue

        for position in range(embedding_dimension):
            order[position] = position
        for position in range(1, embedding_dimension):
            current_index = order[position]
            current_value = signal[start + current_index * delay]
            cursor = position - 1
            while cursor >= 0:
                previous_index = order[cursor]
                previous_value = signal[start + previous_index * delay]
                if current_value < previous_value:
                    order[cursor + 1] = previous_index
                    cursor -= 1
                else:
                    break
            order[cursor + 1] = current_index

        rank = 0
        factorial_weight = 1
        for position in range(embedding_dimension - 2, -1, -1):
            factorial_weight *= embedding_dimension - 1 - position
            inversions = 0
            for right in range(position + 1, embedding_dimension):
                if order[right] < order[position]:
                    inversions += 1
            rank += inversions * factorial_weight
        counts[rank] += np.uint64(1)

    return counts, tied_windows, first_tied_window


def _ordinal_pattern_counts_python(
    signal: np.ndarray,
    embedding_dimension: int,
    delay: int,
    tie_policy_code: int,
) -> tuple[np.ndarray, int, int]:
    state_count = _factorial(embedding_dimension)
    counts = np.zeros(state_count, dtype=np.uint64)
    total_windows = signal.size - (embedding_dimension - 1) * delay
    tied_windows = 0
    first_tied_window = -1

    for start in range(total_windows):
        values = [
            float(signal[start + position * delay])
            for position in range(embedding_dimension)
        ]
        tied = len(set(values)) != embedding_dimension
        if tied:
            tied_windows += 1
            if first_tied_window < 0:
                first_tied_window = start
            if tie_policy_code in {1, 2}:
                continue
        order = sorted(range(embedding_dimension), key=lambda index: (values[index], index))
        rank = 0
        for position in range(embedding_dimension - 1):
            inversions = sum(
                order[right] < order[position]
                for right in range(position + 1, embedding_dimension)
            )
            rank += inversions * math.factorial(embedding_dimension - 1 - position)
        counts[rank] += np.uint64(1)
    return counts, tied_windows, first_tied_window


def _prepare_trajectory(
    data: Sequence[float] | np.ndarray | TrajectoryInput,
    *,
    component: int | str | None,
    sampling: str,
    projection: str,
) -> tuple[np.ndarray, TrajectoryInput, int, str, str]:
    if isinstance(data, TrajectoryInput):
        trajectory = data
        if component is None:
            if trajectory.dimension != 1:
                raise ValueError(
                    "component is required for a multivariable TrajectoryInput."
                )
            component_index = 0
        elif isinstance(component, str):
            try:
                component_index = trajectory.projection.index(component)
            except ValueError as exc:
                raise KeyError(f"Unknown projection label: {component!r}.") from exc
        else:
            if isinstance(component, (bool, np.bool_)):
                raise TypeError("component must be an integer index or projection label.")
            try:
                component_index = int(operator_index(component))
            except TypeError as exc:
                raise TypeError(
                    "component must be an integer index or projection label."
                ) from exc
            if component_index < 0 or component_index >= trajectory.dimension:
                raise IndexError("component index is outside the trajectory dimension.")
        signal = trajectory.component(component_index)
        projection_description = trajectory.projection[component_index]
        if trajectory.sampled_uniformly:
            sampling_description = (
                f"uniform {trajectory.time_coordinate}; "
                f"step={trajectory.uniform_step:.17g}"
            )
        else:
            sampling_description = f"irregular {trajectory.time_coordinate}"
        return (
            signal,
            trajectory,
            component_index,
            sampling_description,
            projection_description,
        )

    if component is not None:
        raise ValueError("component is only valid with TrajectoryInput data.")
    raw = np.asarray(data)
    if raw.ndim != 1:
        raise ValueError("data must be a one-dimensional scalar signal.")
    sampling_description = _nonempty_text(sampling, name="sampling")
    projection_description = _nonempty_text(projection, name="projection")
    trajectory = TrajectoryInput(
        t=np.arange(raw.size, dtype=np.float64),
        x=raw,
        system_kind="sampled_data",
        time_coordinate="iteration_index",
        projection=(projection_description,),
        metadata={"sampling_description": sampling_description},
    )
    return (
        trajectory.component(0),
        trajectory,
        0,
        sampling_description,
        projection_description,
    )


def _backend_name_for_envelope(backend: str) -> str:
    if backend == "native_c":
        return "hafo_c"
    if backend in {"numba", "numba_fallback"}:
        return "hafo_numba"
    return "hafo_python"


@dataclass(frozen=True, slots=True)
class OrdinalPatternDistribution:
    """Dense ordinal-pattern histogram indexed by lexicographic Lehmer rank."""

    counts: np.ndarray
    probabilities: np.ndarray
    sample_count: int
    embedding_dimension: int
    delay: int
    tie_policy: str
    total_windows: int
    valid_windows: int
    tied_windows: int
    omitted_windows: int
    possible_patterns: int
    observed_patterns: int
    missing_patterns: int
    requested_backend: str
    backend: str
    sampling: str
    projection: str
    trajectory_fingerprint: str
    trajectory_system_kind: str
    derivative_definition: str | None
    memory_policy: str
    status: str
    warnings: tuple[str, ...] = ()
    references: tuple[str, ...] = PERMUTATION_ENTROPY_REFERENCE_DOIS
    evidence_scope: str = PERMUTATION_ENTROPY_EVIDENCE_SCOPE
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        counts = _readonly_array(self.counts, np.uint64)
        probabilities = _readonly_array(self.probabilities, np.float64)
        if counts.ndim != 1 or probabilities.shape != counts.shape:
            raise ValueError("counts and probabilities must be aligned vectors.")
        if counts.size != self.possible_patterns:
            raise ValueError("counts length must equal possible_patterns.")
        expected_windows = self.sample_count - (self.embedding_dimension - 1) * self.delay
        if expected_windows != self.total_windows:
            raise ValueError(
                "total_windows must match sample_count, embedding_dimension, and delay."
            )
        if int(np.sum(counts, dtype=np.uint64)) != self.valid_windows:
            raise ValueError("counts must sum to valid_windows.")
        if not np.all(np.isfinite(probabilities)) or np.any(probabilities < 0.0):
            raise ValueError("probabilities must be finite and nonnegative.")
        if not np.isclose(float(np.sum(probabilities)), 1.0, rtol=0.0, atol=1e-12):
            raise ValueError("probabilities must sum to one.")
        object.__setattr__(self, "counts", counts)
        object.__setattr__(self, "probabilities", probabilities)
        object.__setattr__(self, "warnings", tuple(self.warnings))
        object.__setattr__(self, "references", tuple(self.references))
        object.__setattr__(self, "metadata", _readonly_mapping(self.metadata))

    def as_analysis_result(self) -> AnalysisResult:
        return AnalysisResult(
            method="bandt_pompe_ordinal_pattern_distribution",
            values={
                "counts": self.counts,
                "probabilities": self.probabilities,
                "sample_count": self.sample_count,
                "valid_windows": self.valid_windows,
                "tied_windows": self.tied_windows,
            },
            parameters={
                "embedding_dimension": self.embedding_dimension,
                "delay": self.delay,
                "tie_policy": self.tie_policy,
                "possible_patterns": self.possible_patterns,
                "sampling": self.sampling,
                "projection": self.projection,
            },
            backend=_backend_name_for_envelope(self.backend),
            status="finite_numerical_diagnostic",
            trajectory_fingerprint=self.trajectory_fingerprint,
            package_versions_and_hashes={
                "numpy": np.__version__,
                "numba": numba.__version__,
                "native_build": self.metadata.get("native_build"),
            },
            warnings=self.warnings,
            references=self.references,
            evidence_scope=self.evidence_scope,
        )


@dataclass(frozen=True, slots=True)
class PermutationEntropyResult:
    """Plug-in Shannon entropy of a declared ordinal-pattern distribution."""

    distribution: OrdinalPatternDistribution
    entropy: float
    normalized_entropy: float
    maximum_entropy: float
    log_base: float
    estimator: str = "plugin"
    normalization: str = "log_factorial_outcome_space"
    status: str = "ok"
    evidence_scope: str = PERMUTATION_ENTROPY_EVIDENCE_SCOPE
    warnings: tuple[str, ...] = ()
    references: tuple[str, ...] = PERMUTATION_ENTROPY_REFERENCE_DOIS
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        for name in ("entropy", "normalized_entropy", "maximum_entropy", "log_base"):
            if not np.isfinite(float(getattr(self, name))):
                raise ValueError(f"{name} must be finite.")
        if self.entropy < 0.0 or self.maximum_entropy <= 0.0:
            raise ValueError("entropy values must respect the finite Shannon range.")
        if self.normalized_entropy < -2e-15 or self.normalized_entropy > 1.0 + 2e-15:
            raise ValueError("normalized_entropy must lie in [0, 1].")
        object.__setattr__(self, "warnings", tuple(self.warnings))
        object.__setattr__(self, "references", tuple(self.references))
        object.__setattr__(self, "metadata", _readonly_mapping(self.metadata))

    @property
    def backend(self) -> str:
        """Actual backend used to construct the ordinal distribution."""

        return self.distribution.backend

    @property
    def trajectory_fingerprint(self) -> str:
        """Fingerprint of the complete source trajectory contract."""

        return self.distribution.trajectory_fingerprint

    @property
    def sampling(self) -> str:
        """Sampling description inherited from the source trajectory."""

        return self.distribution.sampling

    def as_analysis_result(self) -> AnalysisResult:
        distribution = self.distribution
        return AnalysisResult(
            method="bandt_pompe_permutation_entropy",
            values={
                "entropy": self.entropy,
                "normalized_entropy": self.normalized_entropy,
                "maximum_entropy": self.maximum_entropy,
                "counts": distribution.counts,
                "probabilities": distribution.probabilities,
            },
            parameters={
                "embedding_dimension": distribution.embedding_dimension,
                "delay": distribution.delay,
                "tie_policy": distribution.tie_policy,
                "log_base": self.log_base,
                "estimator": self.estimator,
                "normalization": self.normalization,
                "sampling": distribution.sampling,
                "projection": distribution.projection,
                "provenance": distribution.metadata,
            },
            backend=_backend_name_for_envelope(distribution.backend),
            status="finite_numerical_diagnostic",
            trajectory_fingerprint=distribution.trajectory_fingerprint,
            package_versions_and_hashes={
                "numpy": np.__version__,
                "numba": numba.__version__,
                "native_build": distribution.metadata.get("native_build"),
            },
            warnings=self.warnings,
            references=self.references,
            evidence_scope=self.evidence_scope,
        )


def ordinal_pattern_distribution(
    data: Sequence[float] | np.ndarray | TrajectoryInput,
    *,
    component: int | str | None = None,
    embedding_dimension: int = 3,
    delay: int = 1,
    tie_policy: TiePolicy = "stable_index",
    backend: Backend = "auto",
    fallback: bool = True,
    sampling: str = "sample index",
    projection: str = "supplied scalar signal",
) -> OrdinalPatternDistribution:
    """Estimate a dense Bandt--Pompe ordinal-pattern distribution.

    Each forward window is ``x[s + k*delay]`` for ``k=0,...,m-1``. Pattern
    indices are lexicographic Lehmer ranks of the stable ascending argsort.
    Equal values are never handled silently: callers select temporal stable
    ordering, omission, or rejection.
    """

    dimension = _strict_integer(
        embedding_dimension,
        name="embedding_dimension",
        minimum=2,
        maximum=PERMUTATION_ENTROPY_MAX_EMBEDDING_DIMENSION,
    )
    lag = _strict_integer(delay, name="delay", minimum=1)
    policy, policy_code = _normalize_tie_policy(tie_policy)
    requested_backend = _normalize_backend(backend)
    if not isinstance(fallback, (bool, np.bool_)):
        raise TypeError("fallback must be Boolean.")

    signal, trajectory, component_index, sampling_text, projection_text = (
        _prepare_trajectory(
            data,
            component=component,
            sampling=sampling,
            projection=projection,
        )
    )
    total_windows = signal.size - (dimension - 1) * lag
    if total_windows < 1:
        raise ValueError(
            "data is too short for the selected embedding_dimension and delay."
        )

    native_metadata: Mapping[str, Any] | None = None
    selected_backend = requested_backend
    if requested_backend == "auto":
        selected_backend = _automatic_backend(total_windows, dimension)

    if selected_backend == "python":
        counts, tied_windows, first_tied_window = _ordinal_pattern_counts_python(
            signal,
            dimension,
            lag,
            policy_code,
        )
        actual_backend = "python"
    elif selected_backend == "numba":
        counts, tied_windows, first_tied_window = _ordinal_pattern_counts_numba(
            signal,
            dimension,
            lag,
            policy_code,
        )
        actual_backend = "numba"
    else:
        from .native_permutation_entropy import native_permutation_counts

        native_result = native_permutation_counts(
            signal,
            embedding_dimension=dimension,
            delay=lag,
            tie_policy=policy,
            fallback=bool(fallback),
        )
        counts = np.asarray(native_result.counts, dtype=np.uint64)
        tied_windows = int(native_result.tied_windows)
        first_tied_window = -1
        actual_backend = (
            "native_c" if native_result.backend == "native_c" else "numba"
        )
        native_metadata = (
            asdict(native_result.build)
            if is_dataclass(native_result.build)
            else {"build": repr(native_result.build)}
        )

    tied_windows = int(tied_windows)
    if policy == "raise" and tied_windows:
        location = (
            ""
            if first_tied_window < 0
            else f"; first_tied_window={first_tied_window}"
        )
        raise ValueError(
            "tie_policy='raise' rejected ordinal windows containing equal "
            f"values (tied_windows={tied_windows}{location})."
        )
    valid_windows = int(np.sum(counts, dtype=np.uint64))
    if valid_windows < 1:
        raise ValueError(
            "No valid ordinal windows remain under the selected tie_policy."
        )
    possible_patterns = _factorial(dimension)
    probabilities = np.asarray(counts, dtype=np.float64) / float(valid_windows)
    observed_patterns = int(np.count_nonzero(counts))
    omitted_windows = tied_windows if policy == "omit" else 0

    warnings = list(trajectory.scientific_warnings)
    warnings.append(
        "The relative-frequency plug-in distribution is finite-sample and "
        "uncorrected; overlapping ordinal windows are statistically dependent."
    )
    warnings.append(
        "Permutation entropy is not by itself proof of chaos, attraction, or hiddenness."
    )
    if tied_windows:
        warnings.append(
            f"{tied_windows} ordinal windows contained exact ties and were handled "
            f"with tie_policy={policy!r}."
        )
        if policy == "stable_index":
            warnings.append(
                "stable_index orders equal values by their original position in "
                "the ordinal window; quantized data require tie-policy sensitivity."
            )
    if valid_windows < possible_patterns:
        warnings.append(
            "The number of valid windows is smaller than the factorial outcome "
            "space; missing patterns are therefore strongly sample-limited."
        )

    trajectory_metadata = trajectory.to_serializable()
    trajectory_metadata.pop("t")
    trajectory_metadata.pop("x")
    metadata: dict[str, Any] = {
        "ordinal_encoding": "lexicographic_lehmer_rank_of_stable_argsort",
        "window_order": "forward_x_s_plus_k_delay",
        "component_index": component_index,
        "max_embedding_dimension": PERMUTATION_ENTROPY_MAX_EMBEDDING_DIMENSION,
        "max_pattern_states": PERMUTATION_ENTROPY_MAX_PATTERN_STATES,
        "trajectory_contract": trajectory_metadata,
        "provenance": {
            "input_contract": (
                "TrajectoryInput"
                if isinstance(data, TrajectoryInput)
                else "raw_scalar_series"
            ),
            "component_index": component_index,
            "trajectory": trajectory_metadata,
        },
        "execution": {
            "requested_backend": requested_backend,
            "selected_backend": selected_backend,
            "auto_policy": (
                "dimension_aware_native_window_threshold_otherwise_numba"
                if requested_backend == "auto"
                else "caller_selected"
            ),
            "auto_native_window_threshold": (
                PERMUTATION_ENTROPY_NATIVE_AUTO_WINDOW_THRESHOLDS[dimension]
                if requested_backend == "auto"
                else None
            ),
        },
    }
    if native_metadata is not None:
        metadata["native_build"] = dict(native_metadata)

    return OrdinalPatternDistribution(
        counts=counts,
        probabilities=probabilities,
        sample_count=int(signal.size),
        embedding_dimension=dimension,
        delay=lag,
        tie_policy=policy,
        total_windows=int(total_windows),
        valid_windows=valid_windows,
        tied_windows=tied_windows,
        omitted_windows=omitted_windows,
        possible_patterns=possible_patterns,
        observed_patterns=observed_patterns,
        missing_patterns=possible_patterns - observed_patterns,
        requested_backend=requested_backend,
        backend=actual_backend,
        sampling=sampling_text,
        projection=projection_text,
        trajectory_fingerprint=trajectory.fingerprint(),
        trajectory_system_kind=trajectory.system_kind,
        derivative_definition=trajectory.derivative_definition,
        memory_policy=trajectory.memory_policy,
        status="ok",
        warnings=tuple(warnings),
        metadata=metadata,
    )


def permutation_entropy_from_distribution(
    distribution: OrdinalPatternDistribution,
    *,
    log_base: float = 2.0,
) -> PermutationEntropyResult:
    """Compute plug-in Shannon entropy from an existing pattern distribution."""

    if not isinstance(distribution, OrdinalPatternDistribution):
        raise TypeError("distribution must be an OrdinalPatternDistribution.")
    if isinstance(log_base, (bool, np.bool_)):
        raise TypeError("log_base must be a real number greater than one.")
    try:
        base = float(log_base)
    except (TypeError, ValueError) as exc:
        raise TypeError("log_base must be a real number greater than one.") from exc
    if not np.isfinite(base) or base <= 1.0:
        raise ValueError("log_base must be finite and greater than one.")

    positive = distribution.probabilities[distribution.probabilities > 0.0]
    logarithm = math.log(base)
    entropy = float(-np.sum(positive * np.log(positive)) / logarithm)
    maximum_entropy = float(math.log(distribution.possible_patterns) / logarithm)
    normalized_entropy = float(entropy / maximum_entropy)
    if -2e-15 <= normalized_entropy < 0.0:
        normalized_entropy = 0.0
    if 1.0 < normalized_entropy <= 1.0 + 2e-15:
        normalized_entropy = 1.0

    return PermutationEntropyResult(
        distribution=distribution,
        entropy=entropy,
        normalized_entropy=normalized_entropy,
        maximum_entropy=maximum_entropy,
        log_base=base,
        warnings=distribution.warnings,
        metadata={
            "formula": "-sum(p*log_base(p)) for p>0",
            "normalization_denominator": (
                "log_base(factorial(embedding_dimension))"
            ),
            "finite_sample_bias_correction": "none",
        },
    )


def permutation_entropy(
    data: Sequence[float] | np.ndarray | TrajectoryInput,
    *,
    component: int | str | None = None,
    embedding_dimension: int = 3,
    delay: int = 1,
    tie_policy: TiePolicy = "stable_index",
    log_base: float = 2.0,
    backend: Backend = "auto",
    fallback: bool = True,
    sampling: str = "sample index",
    projection: str = "supplied scalar signal",
) -> PermutationEntropyResult:
    """Estimate a Bandt--Pompe distribution and its plug-in Shannon entropy."""

    distribution = ordinal_pattern_distribution(
        data,
        component=component,
        embedding_dimension=embedding_dimension,
        delay=delay,
        tie_policy=tie_policy,
        backend=backend,
        fallback=fallback,
        sampling=sampling,
        projection=projection,
    )
    return permutation_entropy_from_distribution(distribution, log_base=log_base)


__all__ = [
    "PERMUTATION_ENTROPY_EVIDENCE_SCOPE",
    "PERMUTATION_ENTROPY_MAX_EMBEDDING_DIMENSION",
    "PERMUTATION_ENTROPY_MAX_PATTERN_STATES",
    "PERMUTATION_ENTROPY_NATIVE_AUTO_MIN_WINDOWS",
    "PERMUTATION_ENTROPY_NATIVE_AUTO_WINDOW_THRESHOLDS",
    "PERMUTATION_ENTROPY_REFERENCE_DOIS",
    "OrdinalPatternDistribution",
    "PermutationEntropyResult",
    "ordinal_pattern_distribution",
    "permutation_entropy",
    "permutation_entropy_from_distribution",
]
