"""Advanced recurrence plots and recurrence-quantification analysis.

Stability: experimental

The routines in this module consume *sampled trajectories*.  They are equally
applicable to trajectories generated by integer- and fractional-order solvers,
but the resulting statistics are finite trajectory diagnostics: they do not
prove chaos, hiddenness, or that a projected fractional trajectory is a
Markovian state.

The mathematical definitions follow the recurrence-plot construction of
Eckmann, Kamphorst and Ruelle [1] and the RQA review of Marwan et al. [2].  The
public separation between auto-, cross- and joint-recurrence constructors was
inspired by RecurrenceAnalysis.jl's documented terminology [3]; this is an
independent implementation and does not copy its source code.

References
----------
[1] J.-P. Eckmann, S. O. Kamphorst, and D. Ruelle, "Recurrence Plots of
    Dynamical Systems," Europhysics Letters 4 (1987), 973--977.
    https://doi.org/10.1209/0295-5075/4/9/004
[2] N. Marwan, M. C. Romano, M. Thiel, and J. Kurths, "Recurrence plots for
    the analysis of complex systems," Physics Reports 438 (2007), 237--329.
    https://doi.org/10.1016/j.physrep.2006.11.001
[3] JuliaDynamics, RecurrenceAnalysis.jl documentation.
    https://juliadynamics.github.io/DynamicalSystemsDocs.jl/recurrenceanalysis/stable/
"""

from __future__ import annotations

from dataclasses import dataclass
from math import ceil
from operator import index as operator_index
from typing import Literal

import numpy as np
from numba import njit, prange


Metric = Literal["euclidean", "chebyshev", "manhattan"]
Backend = Literal["auto", "numba", "numpy"]

_METRIC_CODES: dict[str, int] = {
    "euclidean": 0,
    "chebyshev": 1,
    "manhattan": 2,
}

_REFERENCES = (
    "eckmann_kamphorst_ruelle_1987",
    "marwan_romano_thiel_kurths_2007",
    "recurrenceanalysisjl_documentation",
)

_DIAGNOSTIC_SCOPE = (
    "finite sampled-trajectory diagnostic; not proof of chaos or hiddenness"
)
_FRACTIONAL_WARNING = (
    "a projected fractional trajectory need not be a Markovian state because "
    "fractional dynamics retain history"
)


@dataclass(frozen=True, slots=True)
class AdvancedRecurrenceMatrix:
    """A dense Boolean recurrence matrix plus its reproducibility contract.

    ``theiler_window=None`` includes every matrix entry.  An integer ``w >= 0``
    excludes entries satisfying ``abs(row - column) <= w``.  For a rectangular
    cross-recurrence matrix this is explicitly an *index-aligned* policy; users
    must align or resample physical times before requesting that exclusion.
    """

    matrix: np.ndarray
    mode: Literal["auto", "cross", "joint"]
    metric: Metric
    radius: float | tuple[float, ...]
    threshold_policy: Literal["fixed_radius", "global_target_rate"]
    target_recurrence_rate: float | None
    achieved_recurrence_rate: float
    recurrent_points: int
    eligible_points: int
    theiler_window: int | None
    source_shapes: tuple[tuple[int, int], ...]
    sampling: str
    projection: str
    backend: Literal["numba", "numpy"]
    block_rows: int
    joint_policy: str | None = None
    tie_policy: str = "radius_inclusive"
    status: str = "finite_numerical_diagnostic"
    references: tuple[str, ...] = _REFERENCES

    def __post_init__(self) -> None:
        matrix = np.asarray(self.matrix, dtype=np.bool_)
        if matrix.ndim != 2 or matrix.shape[0] < 1 or matrix.shape[1] < 1:
            raise ValueError("matrix must be a non-empty two-dimensional Boolean array.")
        immutable = (
            matrix
            if matrix.flags.c_contiguous and not matrix.flags.writeable
            else np.array(matrix, dtype=np.bool_, order="C", copy=True)
        )
        recurrent = int(np.count_nonzero(immutable))
        expected_eligible = _eligible_count(
            immutable.shape[0], immutable.shape[1], self.theiler_window
        )
        if expected_eligible < 1:
            raise ValueError("recurrence matrix must contain at least one eligible entry.")
        if recurrent != self.recurrent_points:
            raise ValueError("recurrent_points is inconsistent with matrix.")
        if expected_eligible != self.eligible_points:
            raise ValueError("eligible_points is inconsistent with matrix and Theiler policy.")
        expected_rate = recurrent / expected_eligible
        if not np.isclose(
            expected_rate,
            self.achieved_recurrence_rate,
            rtol=0.0,
            atol=8.0 * np.finfo(float).eps,
        ):
            raise ValueError("achieved_recurrence_rate is inconsistent with matrix.")
        if self.theiler_window is not None:
            excluded = ~_eligible_mask(
                0, immutable.shape[0], immutable.shape[1], self.theiler_window
            )
            if np.any(immutable[excluded]):
                raise ValueError("matrix contains recurrence points inside its Theiler window.")
        immutable.flags.writeable = False
        object.__setattr__(self, "matrix", immutable)

    @property
    def metadata(self) -> dict[str, object]:
        """Return JSON-friendly provenance and interpretation metadata."""

        return {
            "mode": self.mode,
            "matrix_shape": tuple(int(v) for v in self.matrix.shape),
            "source_shapes": self.source_shapes,
            "metric": self.metric,
            "threshold": {
                "policy": self.threshold_policy,
                "radius": self.radius,
                "target_global_rate": self.target_recurrence_rate,
                "achieved_global_rate": self.achieved_recurrence_rate,
                "tie_policy": self.tie_policy,
            },
            "theiler": {
                "window": self.theiler_window,
                "policy": (
                    "include_all_entries"
                    if self.theiler_window is None
                    else "exclude_abs_row_minus_column_le_window"
                ),
                "convention": (
                    "HAFO w excludes abs(row-column)<=w; w=0 excludes the LOI. "
                    "RecurrenceAnalysis.jl theiler=0 includes the LOI, so its "
                    "equivalent integer is w+1 when HAFO w is not None."
                ),
            },
            "sampling": self.sampling,
            "projection": self.projection,
            "joint_policy": self.joint_policy,
            "backend": self.backend,
            "block_rows": self.block_rows,
            "diagnostic_scope": _DIAGNOSTIC_SCOPE,
            "fractional_state_warning": _FRACTIONAL_WARNING,
            "references": self.references,
        }


@dataclass(frozen=True, slots=True)
class AdvancedRQAResult:
    """Advanced recurrence-quantification measures.

    ``trend`` follows the classical RQA/RecurrenceAnalysis.jl convention: it
    pools the two directions at each absolute separation, restricts rectangular
    inputs to their leading largest square, excludes ``trend_border`` outer
    diagonals, and reports recurrence-rate change per 1000 sample indices.
    ``normalized_absolute_trend`` preserves HAFO's separately named scale-free
    slope against separation normalized by the full index span.

    Entropies use the natural logarithm and the empirical distribution of line
    lengths that pass the requested minimum.  ``divergence`` is ``1/Lmax``;
    it is positive infinity when no qualifying diagonal exists.
    """

    recurrence_rate: float
    determinism: float
    mean_diagonal_length: float
    longest_diagonal: int
    divergence: float
    diagonal_entropy: float
    laminarity: float
    trapping_time: float
    longest_vertical: int
    vertical_entropy: float
    trend: float
    normalized_absolute_trend: float
    trend_border: int
    min_diagonal: int
    min_vertical: int
    recurrence: AdvancedRecurrenceMatrix
    status: str = "finite_numerical_diagnostic"

    @property
    def metadata(self) -> dict[str, object]:
        """Return the matrix contract augmented with the RQA conventions."""

        metadata = dict(self.recurrence.metadata)
        metadata["rqa"] = {
            "min_diagonal": self.min_diagonal,
            "min_vertical": self.min_vertical,
            "entropy_logarithm": "natural",
            "empty_entropy": "NaN because an empty line-length distribution is undefined",
            "divergence": "1 / longest qualifying diagonal; inf if absent",
            "trend": (
                "classical pooled diagonal-density slope per 1000 sample indices; "
                f"outer border={self.trend_border}; rectangular input uses leading largest square"
            ),
            "normalized_absolute_trend": (
                "HAFO scale-free OLS slope against normalized absolute separation; "
                "reported separately from classical TREND"
            ),
        }
        return metadata


def _as_trajectory(points: np.ndarray, name: str) -> np.ndarray:
    values = np.asarray(points, dtype=np.float64)
    if values.ndim == 1:
        values = values[:, None]
    if values.ndim != 2 or values.shape[0] < 1 or values.shape[1] < 1:
        raise ValueError(f"{name} must have shape (n_samples,) or (n_samples, n_features).")
    if not np.all(np.isfinite(values)):
        raise ValueError(f"{name} must contain only finite values.")
    return np.ascontiguousarray(values)


def _strict_integer(value: int, name: str, *, minimum: int | None = None) -> int:
    if isinstance(value, (bool, np.bool_)):
        raise TypeError(f"{name} must be an integer, not Boolean.")
    try:
        result = operator_index(value)
    except TypeError as exc:
        raise TypeError(f"{name} must be an integer.") from exc
    if minimum is not None and result < minimum:
        raise ValueError(f"{name} must be at least {minimum}.")
    return int(result)


def _validate_common_options(
    *,
    metric: str,
    theiler_window: int | None,
    max_bytes: int,
    max_threshold_bytes: int,
    backend: str,
    sampling: str,
    projection: str,
) -> tuple[Metric, int | None, int, int, Literal["numba", "numpy"], str, str]:
    if not isinstance(metric, str):
        raise TypeError("metric must be a string.")
    metric_normalized = metric.strip().lower()
    if metric_normalized not in _METRIC_CODES:
        raise ValueError("metric must be 'euclidean', 'chebyshev', or 'manhattan'.")
    if theiler_window is not None:
        theiler_window = _strict_integer(
            theiler_window, "theiler_window", minimum=0
        )
    max_bytes = _strict_integer(max_bytes, "max_bytes", minimum=1)
    max_threshold_bytes = _strict_integer(
        max_threshold_bytes, "max_threshold_bytes", minimum=1
    )
    if not isinstance(backend, str):
        raise TypeError("backend must be a string.")
    backend_normalized = backend.strip().lower()
    if backend_normalized == "auto":
        backend_normalized = "numba"
    if backend_normalized not in {"numba", "numpy"}:
        raise ValueError("backend must be 'auto', 'numba', or 'numpy'.")
    if not isinstance(sampling, str) or not sampling.strip():
        raise ValueError("sampling must be a non-empty provenance description.")
    if not isinstance(projection, str) or not projection.strip():
        raise ValueError("projection must be a non-empty provenance description.")
    return (
        metric_normalized,  # type: ignore[return-value]
        theiler_window,
        max_bytes,
        max_threshold_bytes,
        backend_normalized,  # type: ignore[return-value]
        sampling.strip(),
        projection.strip(),
    )


@njit(cache=True, nogil=True, parallel=True)
def _distance_block_numba(
    left: np.ndarray,
    right: np.ndarray,
    row_start: int,
    row_stop: int,
    metric_code: int,
) -> np.ndarray:
    """Compute a 2-D distance block without an ``N x M x D`` tensor."""

    width = right.shape[0]
    dimension = left.shape[1]
    distances = np.empty((row_stop - row_start, width), dtype=np.float64)
    for local_row in prange(row_stop - row_start):
        row = row_start + local_row
        for column in range(width):
            if metric_code == 1:
                value = 0.0
                for coordinate in range(dimension):
                    difference = abs(left[row, coordinate] - right[column, coordinate])
                    if difference > value:
                        value = difference
            else:
                value = 0.0
                for coordinate in range(dimension):
                    difference = abs(left[row, coordinate] - right[column, coordinate])
                    if metric_code == 0:
                        value += difference * difference
                    else:
                        value += difference
                if metric_code == 0:
                    value = np.sqrt(value)
            distances[local_row, column] = value
    return distances


def _distance_block_numpy(
    left: np.ndarray,
    right: np.ndarray,
    row_start: int,
    row_stop: int,
    metric_code: int,
) -> np.ndarray:
    """Vectorized-by-coordinate fallback with only ``block_rows x M`` buffers."""

    rows = left[row_start:row_stop]
    if metric_code == 1:
        distances = np.zeros((rows.shape[0], right.shape[0]), dtype=np.float64)
        for coordinate in range(left.shape[1]):
            difference = np.abs(rows[:, coordinate, None] - right[None, :, coordinate])
            np.maximum(distances, difference, out=distances)
        return distances
    distances = np.zeros((rows.shape[0], right.shape[0]), dtype=np.float64)
    for coordinate in range(left.shape[1]):
        difference = rows[:, coordinate, None] - right[None, :, coordinate]
        if metric_code == 0:
            distances += difference * difference
        else:
            distances += np.abs(difference)
    if metric_code == 0:
        np.sqrt(distances, out=distances)
    return distances


def _distance_block(
    left: np.ndarray,
    right: np.ndarray,
    row_start: int,
    row_stop: int,
    metric_code: int,
    backend: Literal["numba", "numpy"],
) -> np.ndarray:
    if backend == "numba":
        return _distance_block_numba(left, right, row_start, row_stop, metric_code)
    return _distance_block_numpy(left, right, row_start, row_stop, metric_code)


def _eligible_mask(
    row_start: int,
    row_stop: int,
    columns: int,
    theiler_window: int | None,
) -> np.ndarray | None:
    if theiler_window is None:
        return None
    rows = np.arange(row_start, row_stop, dtype=np.int64)[:, None]
    column_indices = np.arange(columns, dtype=np.int64)[None, :]
    return np.abs(rows - column_indices) > theiler_window


def _eligible_count(rows: int, columns: int, theiler_window: int | None) -> int:
    if theiler_window is None:
        return rows * columns
    count = 0
    for row in range(rows):
        excluded_start = max(0, row - theiler_window)
        excluded_stop = min(columns, row + theiler_window + 1)
        count += columns - max(0, excluded_stop - excluded_start)
    return count


def _resolve_block_rows(rows: int, columns: int, block_rows: int | None) -> int:
    if block_rows is not None:
        block_rows = _strict_integer(block_rows, "block_rows", minimum=1)
        return min(rows, block_rows)
    # Keep the main float64 distance workspace near 8 MiB.
    target_elements = (8 * 1024 * 1024) // np.dtype(np.float64).itemsize
    return max(1, min(rows, target_elements // max(1, columns)))


def _coerce_radii(radius: float | tuple[float, ...], count: int) -> tuple[float, ...]:
    if isinstance(radius, (bool, np.bool_)):
        raise TypeError("radius must be real-valued, not Boolean.")
    if np.isscalar(radius):
        radii = (float(radius),) * count
    else:
        raw_radii = tuple(radius)
        if any(isinstance(value, (bool, np.bool_)) for value in raw_radii):
            raise TypeError("radius values must be real-valued, not Boolean.")
        radii = tuple(float(value) for value in raw_radii)
        if len(radii) != count:
            raise ValueError(f"joint radius must provide exactly {count} component radii.")
    if any(not np.isfinite(value) or value < 0.0 for value in radii):
        raise ValueError("radius values must be finite and non-negative.")
    return radii


def _build_recurrence(
    pairs: tuple[tuple[np.ndarray, np.ndarray], ...],
    *,
    mode: Literal["auto", "cross", "joint"],
    radius: float | tuple[float, ...] | None,
    target_rate: float | None,
    metric: Metric,
    theiler_window: int | None,
    max_bytes: int,
    max_threshold_bytes: int,
    block_rows: int | None,
    backend: Literal["numba", "numpy"],
    sampling: str,
    projection: str,
    source_shapes: tuple[tuple[int, int], ...],
) -> AdvancedRecurrenceMatrix:
    if (radius is None) == (target_rate is None):
        raise ValueError("provide exactly one of radius or target_rate.")
    rows = pairs[0][0].shape[0]
    columns = pairs[0][1].shape[0]
    required_bytes = rows * columns * np.dtype(np.bool_).itemsize
    if required_bytes > max_bytes:
        raise MemoryError(
            f"dense recurrence matrix needs {required_bytes} bytes, "
            f"above max_bytes={max_bytes}."
        )
    actual_block_rows = _resolve_block_rows(rows, columns, block_rows)
    eligible_points = _eligible_count(rows, columns, theiler_window)
    if eligible_points < 1:
        raise ValueError("recurrence construction needs at least one Theiler-eligible entry.")
    metric_code = _METRIC_CODES[metric]

    if radius is not None:
        radii = _coerce_radii(radius, len(pairs))
        selected_radius: float | tuple[float, ...]
        selected_radius = radii[0] if len(radii) == 1 else radii
        threshold_policy: Literal["fixed_radius", "global_target_rate"] = "fixed_radius"
        tie_policy = "radius_inclusive"
    else:
        if isinstance(target_rate, (bool, np.bool_)):
            raise TypeError("target_rate must be real-valued, not Boolean.")
        target_rate = float(target_rate)
        if not np.isfinite(target_rate) or not 0.0 < target_rate <= 1.0:
            raise ValueError("target_rate must be finite and in the interval (0, 1].")
        selection_bytes = eligible_points * np.dtype(np.float64).itemsize
        if selection_bytes > max_threshold_bytes:
            raise MemoryError(
                f"global threshold selection needs {selection_bytes} bytes, "
                f"above max_threshold_bytes={max_threshold_bytes}."
            )
        candidates = np.empty(eligible_points, dtype=np.float64)
        cursor = 0
        for row_start in range(0, rows, actual_block_rows):
            row_stop = min(rows, row_start + actual_block_rows)
            aggregate: np.ndarray | None = None
            for left, right in pairs:
                distances = _distance_block(
                    left, right, row_start, row_stop, metric_code, backend
                )
                if aggregate is None:
                    aggregate = distances
                else:
                    np.maximum(aggregate, distances, out=aggregate)
            assert aggregate is not None
            eligible = _eligible_mask(row_start, row_stop, columns, theiler_window)
            selected = aggregate.ravel() if eligible is None else aggregate[eligible]
            candidates[cursor : cursor + selected.size] = selected
            cursor += selected.size
        requested_points = int(ceil(target_rate * eligible_points))
        rank = requested_points - 1
        selected_radius = float(np.partition(candidates, rank)[rank])
        radii = (selected_radius,) * len(pairs)
        threshold_policy = "global_target_rate"
        tie_policy = "include_all_entries_at_selected_radius"

    matrix = np.zeros((rows, columns), dtype=np.bool_)
    for row_start in range(0, rows, actual_block_rows):
        row_stop = min(rows, row_start + actual_block_rows)
        block = np.ones((row_stop - row_start, columns), dtype=np.bool_)
        for (left, right), component_radius in zip(pairs, radii, strict=True):
            distances = _distance_block(left, right, row_start, row_stop, metric_code, backend)
            block &= distances <= component_radius
        eligible = _eligible_mask(row_start, row_stop, columns, theiler_window)
        if eligible is not None:
            block &= eligible
        matrix[row_start:row_stop] = block

    recurrent_points = int(np.count_nonzero(matrix))
    achieved_rate = recurrent_points / eligible_points if eligible_points else 0.0
    joint_policy = None
    if mode == "joint":
        joint_policy = (
            "logical_and_of_component_auto_recurrences; target-rate mode uses "
            "a common radius on the maximum component distance"
        )
    matrix.flags.writeable = False
    return AdvancedRecurrenceMatrix(
        matrix=matrix,
        mode=mode,
        metric=metric,
        radius=selected_radius,
        threshold_policy=threshold_policy,
        target_recurrence_rate=target_rate,
        achieved_recurrence_rate=float(achieved_rate),
        recurrent_points=recurrent_points,
        eligible_points=eligible_points,
        theiler_window=theiler_window,
        source_shapes=source_shapes,
        sampling=sampling,
        projection=projection,
        backend=backend,
        block_rows=actual_block_rows,
        joint_policy=joint_policy,
        tie_policy=tie_policy,
    )


def auto_recurrence_matrix(
    points: np.ndarray,
    *,
    radius: float | None = None,
    target_rate: float | None = None,
    metric: Metric = "euclidean",
    theiler_window: int | None = 0,
    max_bytes: int = 512 * 1024 * 1024,
    max_threshold_bytes: int = 512 * 1024 * 1024,
    block_rows: int | None = None,
    backend: Backend = "auto",
    sampling: str = "samples supplied in row order",
    projection: str = "full supplied state",
) -> AdvancedRecurrenceMatrix:
    """Build an auto-recurrence matrix from one sampled trajectory.

    Fixed-radius entries satisfy ``distance <= radius``.  In target-rate mode,
    the radius is the smallest global order statistic reaching the requested
    eligible-entry count.  Every tie at that radius is included, so the actual
    rate is deterministic and can be greater than the target.
    """

    values = _as_trajectory(points, "points")
    (
        metric_value,
        theiler_value,
        max_bytes_value,
        max_threshold_bytes_value,
        backend_value,
        sampling_value,
        projection_value,
    ) = _validate_common_options(
        metric=metric,
        theiler_window=theiler_window,
        max_bytes=max_bytes,
        max_threshold_bytes=max_threshold_bytes,
        backend=backend,
        sampling=sampling,
        projection=projection,
    )
    return _build_recurrence(
        ((values, values),),
        mode="auto",
        radius=radius,
        target_rate=target_rate,
        metric=metric_value,
        theiler_window=theiler_value,
        max_bytes=max_bytes_value,
        max_threshold_bytes=max_threshold_bytes_value,
        block_rows=block_rows,
        backend=backend_value,
        sampling=sampling_value,
        projection=projection_value,
        source_shapes=(tuple(values.shape),),
    )


def cross_recurrence_matrix(
    left: np.ndarray,
    right: np.ndarray,
    *,
    radius: float | None = None,
    target_rate: float | None = None,
    metric: Metric = "euclidean",
    theiler_window: int | None = None,
    max_bytes: int = 512 * 1024 * 1024,
    max_threshold_bytes: int = 512 * 1024 * 1024,
    block_rows: int | None = None,
    backend: Backend = "auto",
    sampling: str = "sample-index alignment as supplied",
    projection: str = "common supplied coordinates",
) -> AdvancedRecurrenceMatrix:
    """Build a rectangular cross-recurrence matrix for two trajectories."""

    left_values = _as_trajectory(left, "left")
    right_values = _as_trajectory(right, "right")
    if left_values.shape[1] != right_values.shape[1]:
        raise ValueError("cross-recurrence trajectories must share the feature dimension.")
    (
        metric_value,
        theiler_value,
        max_bytes_value,
        max_threshold_bytes_value,
        backend_value,
        sampling_value,
        projection_value,
    ) = _validate_common_options(
        metric=metric,
        theiler_window=theiler_window,
        max_bytes=max_bytes,
        max_threshold_bytes=max_threshold_bytes,
        backend=backend,
        sampling=sampling,
        projection=projection,
    )
    return _build_recurrence(
        ((left_values, right_values),),
        mode="cross",
        radius=radius,
        target_rate=target_rate,
        metric=metric_value,
        theiler_window=theiler_value,
        max_bytes=max_bytes_value,
        max_threshold_bytes=max_threshold_bytes_value,
        block_rows=block_rows,
        backend=backend_value,
        sampling=sampling_value,
        projection=projection_value,
        source_shapes=(tuple(left_values.shape), tuple(right_values.shape)),
    )


def joint_recurrence_matrix(
    *trajectories: np.ndarray,
    radius: float | tuple[float, ...] | None = None,
    target_rate: float | None = None,
    metric: Metric = "euclidean",
    theiler_window: int | None = 0,
    max_bytes: int = 512 * 1024 * 1024,
    max_threshold_bytes: int = 512 * 1024 * 1024,
    block_rows: int | None = None,
    backend: Backend = "auto",
    sampling: str = "synchronously sampled rows as supplied",
    projection: str = "separate supplied component spaces",
) -> AdvancedRecurrenceMatrix:
    """Build a joint recurrence as the logical AND of component auto-RPs.

    At least two synchronously sampled trajectories are required.  A tuple of
    radii applies separate component thresholds.  A scalar applies a common
    radius.  Target-rate selection also uses a common radius and therefore
    assumes the component distances have been scaled meaningfully; normalize
    heterogeneous component spaces before relying on that mode.
    """

    if len(trajectories) < 2:
        raise ValueError("joint recurrence needs at least two trajectories.")
    values = tuple(
        _as_trajectory(trajectory, f"trajectories[{index}]")
        for index, trajectory in enumerate(trajectories)
    )
    sample_count = values[0].shape[0]
    if any(trajectory.shape[0] != sample_count for trajectory in values[1:]):
        raise ValueError("joint-recurrence trajectories must have equal sample counts.")
    (
        metric_value,
        theiler_value,
        max_bytes_value,
        max_threshold_bytes_value,
        backend_value,
        sampling_value,
        projection_value,
    ) = _validate_common_options(
        metric=metric,
        theiler_window=theiler_window,
        max_bytes=max_bytes,
        max_threshold_bytes=max_threshold_bytes,
        backend=backend,
        sampling=sampling,
        projection=projection,
    )
    pairs = tuple((trajectory, trajectory) for trajectory in values)
    return _build_recurrence(
        pairs,
        mode="joint",
        radius=radius,
        target_rate=target_rate,
        metric=metric_value,
        theiler_window=theiler_value,
        max_bytes=max_bytes_value,
        max_threshold_bytes=max_threshold_bytes_value,
        block_rows=block_rows,
        backend=backend_value,
        sampling=sampling_value,
        projection=projection_value,
        source_shapes=tuple(tuple(trajectory.shape) for trajectory in values),
    )


def _run_lengths(line: np.ndarray) -> np.ndarray:
    padded = np.empty(line.size + 2, dtype=np.bool_)
    padded[0] = False
    padded[-1] = False
    padded[1:-1] = line
    changes = np.diff(padded.astype(np.int8))
    starts = np.flatnonzero(changes == 1)
    stops = np.flatnonzero(changes == -1)
    return stops - starts


def _diagonal_lengths(matrix: np.ndarray) -> np.ndarray:
    parts: list[np.ndarray] = []
    rows, columns = matrix.shape
    for offset in range(-(rows - 1), columns):
        lengths = _run_lengths(np.diagonal(matrix, offset=offset))
        if lengths.size:
            parts.append(lengths)
    return np.concatenate(parts) if parts else np.empty(0, dtype=np.int64)


def _vertical_lengths(matrix: np.ndarray) -> np.ndarray:
    parts: list[np.ndarray] = []
    for column in range(matrix.shape[1]):
        lengths = _run_lengths(matrix[:, column])
        if lengths.size:
            parts.append(lengths)
    return np.concatenate(parts) if parts else np.empty(0, dtype=np.int64)


def _line_entropy(lengths: np.ndarray) -> float:
    if not lengths.size:
        return float("nan")
    _, counts = np.unique(lengths, return_counts=True)
    probabilities = counts.astype(np.float64) / counts.sum()
    return float(-np.sum(probabilities * np.log(probabilities)))


def _normalized_absolute_trend(
    matrix: np.ndarray,
    theiler_window: int | None,
) -> float:
    rows, columns = matrix.shape
    recurrent_by_separation: dict[int, int] = {}
    eligible_by_separation: dict[int, int] = {}
    for offset in range(-(rows - 1), columns):
        separation = abs(offset)
        if theiler_window is not None and separation <= theiler_window:
            continue
        diagonal = np.diagonal(matrix, offset=offset)
        recurrent_by_separation[separation] = (
            recurrent_by_separation.get(separation, 0) + int(np.count_nonzero(diagonal))
        )
        eligible_by_separation[separation] = (
            eligible_by_separation.get(separation, 0) + int(diagonal.size)
        )
    separations = sorted(eligible_by_separation)
    if len(separations) < 2:
        return 0.0
    normalizer = max(rows - 1, columns - 1, 1)
    x = np.asarray(separations, dtype=np.float64) / normalizer
    y = np.asarray(
        [recurrent_by_separation.get(value, 0) / eligible_by_separation[value] for value in separations],
        dtype=np.float64,
    )
    centered_x = x - x.mean()
    denominator = float(np.dot(centered_x, centered_x))
    if denominator == 0.0:
        return 0.0
    return float(np.dot(centered_x, y - y.mean()) / denominator)


def _tau_recurrence(matrix: np.ndarray) -> np.ndarray:
    """Pool the two diagonal directions as in RecurrenceAnalysis.jl ``tau_recurrence``."""

    size = min(matrix.shape)
    square = matrix[:size, :size]
    counts = np.zeros(size, dtype=np.float64)
    for offset in range(-(size - 1), size):
        separation = abs(offset)
        recurrent = float(np.count_nonzero(np.diagonal(square, offset=offset)))
        counts[separation] += recurrent if separation == 0 else 0.5 * recurrent
    return counts / np.arange(size, 0, -1, dtype=np.float64)


def _classical_recurrence_trend(
    matrix: np.ndarray,
    theiler_window: int | None,
    border: int,
) -> float:
    """Return the documented RQA TREND in rate change per 1000 indices."""

    diagonal_rates = _tau_recurrence(matrix)
    julia_theiler = 0 if theiler_window is None else theiler_window + 1
    stop = diagonal_rates.size - border
    if stop - julia_theiler < 2:
        return float("nan")
    selected = diagonal_rates[julia_theiler:stop]
    mean_rate = float(np.mean(selected))
    # Exact one-based convention documented and implemented by
    # RecurrenceAnalysis.jl: delta[d] = d - (b + theiler) / 2.
    one_based_indices = np.arange(julia_theiler + 1, stop + 1, dtype=np.float64)
    delta = one_based_indices - (stop + julia_theiler) / 2.0
    denominator = float(np.dot(delta, delta))
    if denominator == 0.0:
        return float("nan")
    numerator = float(np.dot(delta, selected - mean_rate))
    return 1000.0 * numerator / denominator


def recurrence_quantification_advanced(
    recurrence: AdvancedRecurrenceMatrix,
    *,
    min_diagonal: int = 2,
    min_vertical: int = 2,
    trend_border: int = 10,
) -> AdvancedRQAResult:
    """Compute RR, DET, L, Lmax, DIV, ENTR, LAM, TT, Vmax and TREND.

    The recurrence matrix must come from this module so that the denominator,
    source shapes, threshold policy, Theiler exclusion, sampling and projection
    metadata cannot silently be lost.
    """

    if not isinstance(recurrence, AdvancedRecurrenceMatrix):
        raise TypeError("recurrence must be an AdvancedRecurrenceMatrix.")
    min_diagonal = _strict_integer(min_diagonal, "min_diagonal", minimum=1)
    min_vertical = _strict_integer(min_vertical, "min_vertical", minimum=1)
    trend_border = _strict_integer(trend_border, "trend_border", minimum=0)

    diagonal_lengths = _diagonal_lengths(recurrence.matrix)
    selected_diagonals = diagonal_lengths[diagonal_lengths >= min_diagonal]
    diagonal_points = int(selected_diagonals.sum())
    recurrent_points = recurrence.recurrent_points
    determinism = diagonal_points / recurrent_points if recurrent_points else 0.0
    mean_diagonal = float(selected_diagonals.mean()) if selected_diagonals.size else 0.0
    longest_diagonal = int(selected_diagonals.max()) if selected_diagonals.size else 0
    divergence = 1.0 / longest_diagonal if longest_diagonal else float("inf")

    vertical_lengths = _vertical_lengths(recurrence.matrix)
    selected_verticals = vertical_lengths[vertical_lengths >= min_vertical]
    vertical_points = int(selected_verticals.sum())
    laminarity = vertical_points / recurrent_points if recurrent_points else 0.0
    trapping_time = float(selected_verticals.mean()) if selected_verticals.size else 0.0
    longest_vertical = int(selected_verticals.max()) if selected_verticals.size else 0

    return AdvancedRQAResult(
        recurrence_rate=recurrence.achieved_recurrence_rate,
        determinism=float(determinism),
        mean_diagonal_length=mean_diagonal,
        longest_diagonal=longest_diagonal,
        divergence=float(divergence),
        diagonal_entropy=_line_entropy(selected_diagonals),
        laminarity=float(laminarity),
        trapping_time=trapping_time,
        longest_vertical=longest_vertical,
        vertical_entropy=_line_entropy(selected_verticals),
        trend=_classical_recurrence_trend(
            recurrence.matrix, recurrence.theiler_window, trend_border
        ),
        normalized_absolute_trend=_normalized_absolute_trend(
            recurrence.matrix, recurrence.theiler_window
        ),
        trend_border=trend_border,
        min_diagonal=min_diagonal,
        min_vertical=min_vertical,
        recurrence=recurrence,
    )


__all__ = [
    "AdvancedRecurrenceMatrix",
    "AdvancedRQAResult",
    "auto_recurrence_matrix",
    "cross_recurrence_matrix",
    "joint_recurrence_matrix",
    "recurrence_quantification_advanced",
]
