"""Centralized bibliographic registry for verified academic references."""

REFERENCE_REGISTRY = {
    "leonov_kuznetsov_hidden_definition": {
        "key": "leonov_kuznetsov_hidden_definition",
        "label": "Leonov-Kuznetsov hidden attractor definition",
        "authors": "Leonov, Gennady A. and Kuznetsov, Nikolay V.",
        "year": "2013",
        "title": "Hidden Attractors in Dynamical Systems: From Hidden Oscillations in Hilbert-Kolmogorov, Aizerman, and Kalman Problems to Hidden Chaotic Attractor in Chua Circuits",
        "journal": "International Journal of Bifurcation and Chaos",
        "volume": "23",
        "number": "1",
        "pages": "1330002",
        "doi": "10.1142/S0218127413300024",
        "url": "https://doi.org/10.1142/S0218127413300024",
        "topics": ["hidden_attractor_definition", "self_excited_vs_hidden"],
        "verification_status": "verified",
        "needs_doi_verification": False,
    },
    "kuznetsov_2017_chua_df": {
        "key": "kuznetsov_2017_chua_df",
        "label": "Kuznetsov Describing Function for Chua Circuit",
        "authors": "Kuznetsov, Nikolay V. and Blagov, M. V. and Yuldashev, R. V. and Yuldashev, M. V. and Leonov, G. A.",
        "year": "2017",
        "title": "Localization of hidden Chua attractors by the describing function method",
        "journal": "IFAC-PapersOnLine",
        "volume": "50",
        "number": "1",
        "pages": "15035-15040",
        "doi": "10.1016/j.ifacol.2017.12.015",
        "url": "https://doi.org/10.1016/j.ifacol.2017.12.015",
        "topics": ["describing_function_chua", "hidden_attractor_localization"],
        "verification_status": "verified",
        "needs_doi_verification": False,
    },
    "diethelm_ford_freed_abm_caputo": {
        "key": "diethelm_ford_freed_abm_caputo",
        "label": "Diethelm-Ford-Freed ABM Predictor-Corrector Method",
        "authors": "Diethelm, Kai and Ford, Neville J. and Freed, Alan D.",
        "year": "2002",
        "title": "A Predictor-Corrector Approach for the Numerical Solution of Fractional Differential Equations",
        "journal": "Nonlinear Dynamics",
        "volume": "29",
        "number": "1-4",
        "pages": "3-22",
        "doi": "10.1023/A:1016592217141",
        "url": "https://doi.org/10.1023/A:1016592217141",
        "topics": ["caputo_abm_integration", "fractional_differential_equations"],
        "verification_status": "external_reference_pending",
        "needs_doi_verification": False,
    },
    "danca_2017_fractional_hidden": {
        "key": "danca_2017_fractional_hidden",
        "label": "Danca Hidden Chaotic Attractors in Fractional-Order Systems",
        "authors": "Danca, Marius-F.",
        "year": "2017",
        "title": "Hidden Chaotic Attractors in Fractional-Order Systems",
        "journal": "Nonlinear Dynamics",
        "volume": "89",
        "number": "1",
        "pages": "577-586",
        "doi": "10.1007/s11071-017-3462-1",
        "url": "https://doi.org/10.1007/s11071-017-3462-1",
        "topics": ["fractional_hidden_attractors", "fractional_stability", "fractional_chua"],
        "verification_status": "verified",
        "needs_doi_verification": False,
    },
    "matignon_fractional_stability": {
        "key": "matignon_fractional_stability",
        "label": "Matignon Fractional Stability Results",
        "authors": "Matignon, Denis",
        "year": "1996",
        "title": "Stability Results for Fractional Differential Equations with Applications to Control Processing",
        "journal": "Computational Engineering in Systems Applications",
        "volume": "2",
        "number": "1",
        "pages": "963-968",
        "doi": None,
        "url": "https://www.researchgate.net/publication/229007412_Stability_results_for_fractional_differential_equations_with_applications_to_signal_processing",
        "topics": ["fractional_matignon_stability", "fractional_stability"],
        "verification_status": "external_reference_pending",
        "needs_doi_verification": True,
    },
    "machado_2015_fractional_describing_functions": {
        "key": "machado_2015_fractional_describing_functions",
        "label": "Machado Fractional Describing Functions",
        "authors": "Machado, J. Tenreiro",
        "year": "2015",
        "title": "Fractional order describing functions",
        "journal": "Nonlinear Dynamics",
        "volume": "80",
        "number": "4",
        "pages": "1725-1733",
        "doi": "10.1007/s11071-014-1422-9",
        "url": "https://doi.org/10.1007/s11071-014-1422-9",
        "topics": ["machado_fdf", "describing_functions"],
        "verification_status": "external_reference_pending",
        "needs_doi_verification": False,
    },
    "guan_xie_2025_review": {
        "key": "guan_xie_2025_review",
        "label": "Guan-Xie Review on Hidden Attractor Localization",
        "authors": "Guan, Xinqi and Xie, Yong",
        "year": "2025",
        "title": "A Review on Methods for Localization of Hidden Attractors",
        "journal": "Nonlinear Dynamics",
        "volume": "113",
        "number": "3",
        "pages": "22223-22255",
        "doi": "10.1007/s11071-025-11327-5",
        "url": "https://doi.org/10.1007/s11071-025-11327-5",
        "topics": ["alternative_localization_methods", "hidden_attractors_review"],
        "methods": ["numerical_continuation", "perpetual_point", "critical_velocity_surface", "connecting_curve"],
        "verification_status": "verified",
        "needs_doi_verification": False,
    },
    "wu_2023_fractional_chua_arctan": {
        "key": "wu_2023_fractional_chua_arctan",
        "label": "Wu et al. Fractional Chua with Arctan Nonlinearity",
        "authors": "Wu, G. and Sene, N. and others",
        "year": "2023",
        "title": "Hidden attractors in a new fractional-order Chua system with arctan nonlinearity and its DSP implementation",
        "journal": "Chaos, Solitons & Fractals",
        "volume": "175",
        "pages": "113941",
        "doi": "10.1016/j.chaos.2023.113941",
        "url": "https://doi.org/10.1016/j.chaos.2023.113941",
        "topics": ["wu_fractional_chua_arctan", "fractional_chua"],
        "verification_status": "verified",
        "needs_doi_verification": False,
    }
}
